"""
Banana Ripeness Detection - Project Setup Script
=================================================
This script creates the required folder structure for training a YOLOv8 
object detection model to classify bananas into 4 ripeness stages.

Classes:
    0: Unripe   (Green bananas)
    1: Ripe     (Yellow bananas)
    2: Overripe (Yellow with brown spots)
    3: Rotten   (Mostly brown/black bananas)

Run this script FIRST before collecting and annotating your images.
"""

import os
from pathlib import Path


def create_project_structure():
    """
    Creates the YOLO-compatible dataset folder structure.
    
    Structure:
    banana_detection/
    ├── dataset/
    │   ├── images/
    │   │   ├── train/    <- Put ~80% of your images here
    │   │   └── val/      <- Put ~20% of your images here
    │   └── labels/
    │       ├── train/    <- Annotation .txt files for train images
    │       └── val/      <- Annotation .txt files for val images
    ├── runs/             <- Training outputs will be saved here
    ├── models/           <- Store your trained models here
    └── data.yaml         <- Auto-generated by train.py
    """
    
    # Base directory
    base_dir = Path("banana_detection")
    
    # Define all required directories
    directories = [
        base_dir / "dataset" / "images" / "train",
        base_dir / "dataset" / "images" / "val",
        base_dir / "dataset" / "labels" / "train",
        base_dir / "dataset" / "labels" / "val",
        base_dir / "runs",
        base_dir / "models",
    ]
    
    # Create directories
    for directory in directories:
        directory.mkdir(parents=True, exist_ok=True)
        print(f"✓ Created: {directory}")
    
    # Create a sample annotation file to show the format
    sample_annotation = base_dir / "dataset" / "labels" / "SAMPLE_ANNOTATION.txt"
    sample_content = """# YOLO Annotation Format (DO NOT USE THIS FILE - DELETE IT)
# Each line represents one object in the image:
# <class_id> <x_center> <y_center> <width> <height>
# 
# All values are NORMALIZED (0.0 to 1.0, relative to image dimensions)
#
# Class IDs:
#   0 = Unripe
#   1 = Ripe
#   2 = Overripe
#   3 = Rotten
#
# Example: A ripe banana in the center of the image
# 1 0.5 0.5 0.3 0.15
#
# Example: Two bananas in one image (Unripe and Overripe)
# 0 0.25 0.4 0.2 0.12
# 2 0.75 0.6 0.25 0.14
"""
    sample_annotation.write_text(sample_content)
    print(f"✓ Created sample annotation guide: {sample_annotation}")
    
    print("\n" + "="*60)
    print("PROJECT STRUCTURE CREATED SUCCESSFULLY!")
    print("="*60)
    print(f"\nNext Steps:")
    print(f"1. Collect banana images (aim for 100+ per class)")
    print(f"2. Split images: 80% in 'train', 20% in 'val'")
    print(f"3. Annotate images using LabelImg or Roboflow")
    print(f"4. Run train.py to start training")
    print(f"\nSee ANNOTATION_GUIDE.md for detailed annotation instructions.")
    
    return base_dir


if __name__ == "__main__":
    create_project_structure()
